name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME  : "dev-flask-aplication-packages"
  EB_APLICATION_NAME         : "Myflask"
  EB_ENVIRONMENT_NAME        : "Myflask-env"
  DEPLOY_PACKAGE_NAME        : "flask_app_${{ github.sha }}.zip"      
  AWS_REGION_NAME            : "eu-central-1"
  
on:
  push:
    branches: 
      - master
        
jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
      
    - name: Create ZIP deployment package
      run:  zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

    - name: Configure my AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     : ${{ secrets.My_AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.My_AWS_SECRET_KEY }}
        aws-region            : ${{ env.AWS_REGION_NAME }}    
    
    - name: Copy Deployment package to S7 bucket +
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
  
  
  my_cd_part:
    runs-on: ubuntu-latest
    needs: [my_ci_part]
    
    steps: 
    - name: Configure my AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     : ${{ secrets.My_AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.My_AWS_SECRET_KEY }}
        aws-region            : ${{ env.AWS_REGION_NAME }} 
        
        
    - name: Create new ELasticBeanstalk aws Aplication Versions
      run: |
        aws elasticbeanstalk create-application-version \
        --application-name ${{ env.EB_APLICATION_NAME }} \
        --source-bundle S3Bucket ="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
        --version-label "Ver-${{ github.sha }}" \
        --description "CommitSHA-${{ github.sha }}"       
       
    - name: Deploy new ElasticBeanstalk Application Version
      run:  aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "ver-${{ github.sha }}" 
    
    
    
    
          
          
          
          
          
